server {
    # 1. Cambia el puerto de escucha interno
    listen 80;
    
    # 2. Define el nombre del servidor (opcional pero recomendado)
    server_name localhost;

    # 3. Forzar el puerto en las redirecciones
    port_in_redirect off; 
    
    # Enruta el tráfico principal al contenedor de Angular
    location / {
        proxy_pass http://coretask-frontend:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Enruta las peticiones que empiecen con /api/ al contenedor de Spring Boot
    location /api/ {
        proxy_pass http://coretask-backend:8080/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}